services:
  db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      denarius-net:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      denarius-net:
  receiver:
    build:
      context: .
      dockerfile: dockerfiles/receiver.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      denarius-net:
  scanner:
    build:
      context: .
      dockerfile: dockerfiles/scanner.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      denarius-net:
    volumes:
      - ./scanner/settings:/app/scanner/settings
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
      RABBITMQ_DEFAULT_VHOST:
    networks:
      denarius-net:

networks:
  denarius-net:
