# Generated by Django 3.0.2 on 2020-12-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DucatusTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(default='', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=78)),
                ('state', models.CharField(default='', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ducatus_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange_requests.DucatusUser')),
            ],
        ),
    ]
