# Generated by Django 3.0.2 on 2020-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducatustransfer',
            name='currency',
            field=models.CharField(default='DUC', max_length=50, null=True),
        ),
    ]
