# Generated by Django 3.0.2 on 2020-12-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_ducatustransfer_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducatustransfer',
            name='from_address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ducatustransfer',
            name='number_of_confirmations',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AddField(
            model_name='ducatustransfer',
            name='to_address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ducatustransfer',
            name='tranasction_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
            preserve_default=False,
        ),
    ]
