# Generated by Django 3.0.2 on 2020-12-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_auto_20201216_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ducatustransfer',
            old_name='tranasction_fee',
            new_name='transaction_fee',
        ),
    ]
